#!/bin/bash

set -e

if [[ $TRAVIS_BRANCH != 'master' ]]
then
  exit
fi

# Uploads generated rumpelstiltskin.js to master branch. Thx @erikrose, @pmac, @jwhitlock and @matteocrippa
git checkout master

git config user.name "schalkneethling"
git config user.email "sneethling@mozilla.com"

echo add rumpelstiltskin.js
git add -f rumpelstiltskin.js

echo commit
git commit -m "[auto] [ci skip] Pushing latest compiled rumpelstiltskin.js"

echo push
# Eat output so it doesn't spit out the sensitive GH_TOKEN if something goes wrong:
git push -q -f "https://${GH_TOKEN}@github.com/schalkneethling/rumpelstiltskin.git" master:master > /dev/null 2>&1
